name: RecStudio
options:
  bundleIdPrefix: com.recstudio
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  groupSortPosition: top
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  RecStudio:
    type: application
    platform: macOS
    sources:
      - path: RecStudio
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.recstudio.app
        INFOPLIST_FILE: RecStudio/Info.plist
        CODE_SIGN_ENTITLEMENTS: RecStudio/RecStudio.entitlements
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_IDENTITY: "-"
